name: Sync with Gosh

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
